name: CI
on: push
jobs:
  test-host_machine:
    runs-on: macos-11
    steps:
      - name: Setup the Host Machine
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/hamuyuuki/dotfiles/master/host_machine/setup.sh)"
  test-guest_machine:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup the Guest Machine
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/hamuyuuki/dotfiles/master/guest_machine/setup.sh)"
        env:
          GOROOT: "/usr/lib/go-1.17" # Use the golang-go package
