name: CI
on: push
jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Uninstall the default awscli package
        run: brew uninstall awscli
      - run: /bin/zsh -c "$(curl -fsSL https://raw.githubusercontent.com/hamuyuuki/dotfiles/master/setup.sh)"
