name: CI
on: push
jobs:
  test-host_machine:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run setup.sh
        run: /bin/bash ./host_machine/setup.sh
